### ISSUE TITLE
The library is not working after updating to Google Play services revision 30

### ISSUE THREAD

**Issue by revanaii** [HaxeExtension/extension-googleplayservices-lib#3] opened 2016-05-26 23:28 UTC
Part of the log:

> BUILD FAILED
> {path to the SDK}\android_sdk\tools\ant\build.xml:573: com.android.io.Strea
> mException: java.io.FileNotFoundException: {path to the project}\project\export\android\bin\deps\google-play-services_lib\And
> roidManifest.xml (═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы)
>         at com.android.io.FileWrapper.getContents(FileWrapper.java:93)
>         at com.android.xml.AndroidManifest.getStringValue(AndroidManifest.java:4
> 12)

It seems that 
${ANDROID_SDK}/extras/google/google_play_services/libproject/google-play-services_lib
is not a valid path anymore.
Even more: there's no google-play-services.jar under "google_play_services".
I tried to re-install Google Play services, re-install the whole SDK thing, did not help.
I had to grab the old revision from here manually
https://dl-ssl.google.com/android/repository/google_play_services_8487000_r29.zip
So I'm not sure on which side the problem is, but I thought that it might be a good thing to submit it.

**Comment by fbricker** [comment] 2016-05-27 14:15
Hi, the issue is that google published a **broken version of google-play-services-library** on the android SDK manager (or at least I assume it's a google issue, since version 30 misses the libproject folder, but their online documentation still says you should copy that folder to your project).

**Just for other people reading this post, here is the complete solution:**

If you have package "Google Play Services" version 30, you should downgrade it to version 29 or wait for version 31.

You can get version 29 here:
https://dl-ssl.google.com/android/repository/google_play_services_8487000_r29.zip1

You should place this under:
(ANDROID-SDK-PATH)/extras/google/google_play_services

Finally, make sure this folder exists.
(ANDROID-SDK-PATH)/extras/google/google_play_services/libproject

PS: I'm closing this issue assuming version 31 will fix this. In case version 31 still fails, we'll re-open it.

**Comment by wikiti** [comment] 2016-07-10 22:57
Version 31 has still NOT fixed it.

**Comment by fbricker** [comment] 2016-07-11 11:36
hmmm... looks like we're going to do some big changes on this extension :/

I'll try to take a look on this soon, but if someone has any information to provide or pull request to make, it'll be great.

**Comment by wikiti** [comment] 2016-07-11 12:28
According to [StackOverflow question](http://stackoverflow.com/questions/37310684/missing-sdk-extras-google-google-play-services-libproject-folder-after-updat), google broke gpg-lib into smaller libraries (with `arr` format). Perhaps the anwers to that question may be useful to update this extension.

**Comment by fbricker** [comment] 2016-09-24 05:20
Hi, we've just created a new library called "extension-googleplayservices-basement" and published updates to all libraries using this library to use the new one.

extension-googleplayservices-basement contains the smaller libraries in which google separated, and will include just the required pieces to your projects according to each extension requirements.

This is good, since you'll be saving some MB on your games 👍 

So, to be clear: 
* Just doing haxelib upgrade will upgrade google play games, amazon sns, facebookads, and admob extensions to the last SDK versions (no API changes were made, so you shouldn't have issues at all). 
* extension-googleplayservices-lib is official deprecated (we'll leave it working for some time until most people migrates to the new extension).
* Now the SDKs comes inside the extensions (you won't need to download anything from your Android Device Manager).

**Closed as completed by fbricker** 2016-09-24 05:20 UTC

**Comment by mastef** [comment] 2016-10-11 06:00
@fbricker could you be so kind and add a depreciation notice in the Readme.md ? Just ran into this as https://github.com/emibap/GAnalytics is not updated yet to the basement lib, and had to find this out the hard way by going through closed issues 😅

**Comment by fbricker** [comment] 2016-10-11 13:46
You're right... I'll add that notice 👍
